In [3]:
import numpy as np

In [36]:
import itertools

In [3]:
# l = [21,22,23,24]
# n = len(l)

In [4]:
# permutation_order = list(itertools.permutations(list(range(n))))

In [5]:
# permutations = []
# for p in permutation_order:
#     permutations.append([l[i] for i in p])

In [6]:
x = [0,1,1,0]
pihat = [0.5347, 0.4653];
Ahat = np.array([[0.4895, 0.5105], [0.5146, 0.4854]]);

In [7]:
def compute_likelihood(bag_of_nodes, pi_hat, A_hat):
    n = len(bag_of_nodes)
    
    permutation_orders = list(itertools.permutations(list(range(n))))
    
    gamma = np.zeros(n)
    Gamma = np.zeros((n,n))
    
    for order in permutation_orders:
        starting_node = order[0]
        p = pi_hat[bag_of_nodes[starting_node]]
        
        for i in range(1, n):
            p = p * A_hat[bag_of_nodes[order[i - 1]]][bag_of_nodes[order[i]]]
        
        gamma[order[0]] += p
        
        for i in range(1, n):
            Gamma[order[i - 1]][order[i]] += p
    return gamma, Gamma

In [8]:
g, G = compute_likelihood(x, pihat, Ahat)

In [10]:
G

array([[0.        , 0.39919442, 0.39919442, 0.36316843],
       [0.38242365, 0.        , 0.37986534, 0.38242365],
       [0.38242365, 0.37986534, 0.        , 0.38242365],
       [0.36316843, 0.39919442, 0.39919442, 0.        ]])

Array indexing

In [45]:
n = 4
x = np.array([[0,2,2,1,3], [0,2,1,1,3]])
p = np.array([[1,2,3,4,5], [1,1,3,4,5]])
c = np.zeros(n)

In [46]:
for seq, probs in zip(x, p):
    
    for node_id in range(n):
        indexes = [i for i, j in enumerate(seq) if j == node_id]
        c[node_id] += probs[indexes].sum()

In [47]:
c

array([ 2., 11.,  6., 10.])

Matrix indexing

In [7]:
n = 4
x = np.array([[0,2,2,1,3], [0,2,1,1,3]])

In [15]:
chunk = 2
overlap = 1
seq = x[0]

In [55]:
def overlapped_chunks(array, chunk_size = 2, overlap_size = 1):
    return [tuple(array[i:i+chunk_size]) for i in range(0, len(array)-1, chunk_size-overlap_size)]

In [56]:
o = overlapped_chunks(x[0])
o

[(0, 2), (2, 2), (2, 1), (1, 3)]

In [57]:
C = np.random.rand(n,n)

In [58]:
C[o[0][0]][o[0][1]]

0.7315045549130181

In [59]:
C

array([[0.98329935, 0.35359209, 0.73150455, 0.59658271],
       [0.13169447, 0.61879704, 0.00356567, 0.25731214],
       [0.19989227, 0.30510572, 0.79612313, 0.47609517],
       [0.42557832, 0.43022971, 0.60221477, 0.78902869]])

In [60]:
ind = range(n)

In [61]:
indexes = overlapped_chunks(list(ind))

In [62]:
indexes

[(0, 1), (1, 2), (2, 3)]

In [63]:
tuple(reversed(indexes[0]))

(1, 0)

In [64]:
C[indexes[0]]

0.3535920895063711

In [66]:
Z = np.zeros((n,n))

In [67]:
Z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [68]:
list(range(4))

[0, 1, 2, 3]

In [2]:
from scipy.sparse import csr_matrix

In [70]:
csr_matrix(Z)

<4x4 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in Compressed Sparse Row format>

Normalization

In [198]:
def normalize_csr_rows(csr_mat):
    row_sums = np.array(csr_mat.sum(axis=1))[:,0]
    row_indices, col_indices = csr_mat.nonzero()
    csr_mat.data /= row_sums[row_indices]

In [199]:
def normalize_csr_columns(csr_mat):
    col_sums = np.array(csr_mat.sum(axis=0))[0,:]
    row_indices, col_indices = csr_mat.nonzero()
    csr_mat.data /= col_sums[col_indices]

In [200]:
m = csr_matrix(np.random.rand(3,3))
m_1 = m.copy()

In [201]:
print(m.todense())

[[0.45420376 0.10662649 0.24330556]
 [0.02304522 0.35026589 0.14009161]
 [0.62690892 0.19596014 0.14619914]]


In [202]:
normalize_csr_columns(m)

In [203]:
print(m.transpose().todense())

[[0.41135762 0.02087131 0.56777108]
 [0.16332401 0.5365161  0.30015989]
 [0.45941702 0.26452528 0.2760577 ]]


In [204]:
print(m_1.todense())

[[0.45420376 0.10662649 0.24330556]
 [0.02304522 0.35026589 0.14009161]
 [0.62690892 0.19596014 0.14619914]]


In [205]:
normalize_csr_rows(m_1)

In [206]:
print(m_1.todense())

[[0.56483464 0.13259761 0.30256775]
 [0.04488722 0.68224393 0.27286885]
 [0.6469193  0.20221502 0.15086569]]
